# Generated by Django 4.2.5 on 2023-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cata_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cata',
            old_name='data',
            new_name='date',
        ),
        migrations.AddField(
            model_name='cata',
            name='duration',
            field=models.CharField(default='2 horas', max_length=50),
        ),
    ]
