# Generated by Django 4.2.5 on 2023-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cata_slug_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cata',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
