# Generated by Django 4.2.5 on 2023-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cata_slug_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='cata',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
