# Generated by Django 4.2.5 on 2023-09-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_slug_cata_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cata',
            name='slug',
        ),
    ]
