# Generated by Django 4.2.5 on 2023-09-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('bodega', models.CharField(max_length=100)),
                ('grapes', models.CharField(max_length=100)),
                ('denomination', models.CharField(max_length=100)),
                ('crianza', models.CharField(max_length=100)),
            ],
            bases=('store.product',),
        ),
    ]
