# Generated by Django 4.2.5 on 2023-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_vino'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vino',
            name='bodega',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vino',
            name='crianza',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vino',
            name='denomination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vino',
            name='grapes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
